/**
 * Server-side and client-side Amplify utilities.
 * Configures the Amplify client for use in Next.js SSR and CSR contexts.
 */

"use client";

import { Amplify } from "aws-amplify";

let isConfigured = false;

export function configureAmplify() {
  if (isConfigured) return;

  try {
    // amplify_outputs.json is generated by `npx ampx generate outputs`
    // It won't exist until first deployment, so we handle the missing case
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    const outputs = require("../../amplify_outputs.json");
    Amplify.configure(outputs, { ssr: true });
    isConfigured = true;
  } catch {
    console.warn("[Amplify] amplify_outputs.json not found -- Amplify not configured yet. Run npx ampx generate outputs after first deployment.");
  }
}
